# Generated by Django 3.2.16 on 2022-11-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashtoken',
            name='expires_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bkashtoken',
            name='updated_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
