# Generated by Django 3.2.16 on 2022-11-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0003_bkashpaymentrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bkashpaymentrecord',
            old_name='paymentID',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='bkashpaymentrecord',
            old_name='response',
            new_name='payment_response',
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='createTime',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='currency',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='intent',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='merchantInvoiceNumber',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='orgLogo',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='orgName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrecord',
            name='transactionStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
