# Generated by Django 3.2.16 on 2022-11-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0004_auto_20221124_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkashpaymentrecord',
            name='merchant_inovice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bkashpaymentrecord',
            name='transaction_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bkashpaymentrecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bkashpaymentrecord',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
