# Generated by Django 3.2.16 on 2022-11-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0005_auto_20221124_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
