# Generated by Django 3.2.16 on 2022-11-24 06:14

import bkash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0006_errorhandle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashtoken',
            name='refresh_token',
            field=models.TextField(blank=True, verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='bkashtoken',
            name='token',
            field=models.TextField(blank=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='bkashtoken',
            name='token_id',
            field=models.CharField(default=bkash.models.generate_tid, max_length=100, verbose_name='Token ID'),
        ),
    ]
