# Generated by Django 3.2.16 on 2022-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0007_auto_20221124_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
